name:                graten
version:             0.1.0.0
github:              "momohatt/graten"
license:             BSD3
author:              "Momoko Hattori"
maintainer:          "momohatt10@gmail.com"
copyright:           "2022 Momoko Hattori"

extra-source-files:
- README.md
- stub/torch/*.mli
- lib.smtlib

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/momohatt/graten#readme>

dependencies:
- base                  >= 4.7      && < 5.0
- containers            == 0.6.*
- directory             >= 1.2.5    && < 1.4
- extra                 >= 1.0      && < 2.0
- megaparsec            >= 9.0      && < 10.0
- mtl                   >= 2.2      && < 3.0
- optparse-applicative  >= 0.15.0   && < 0.20.0
- parser-combinators    >= 1.0      && < 2.0
- process               >= 1.6.0    && < 1.7
- prettyprinter         >= 1.7.0    && < 2.0
- unix                  == 2.7.*

library:
  source-dirs: src

ghc-options:
- -Wall
- -Wno-name-shadowing

executables:
  graten:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-name-shadowing
    dependencies:
    - graten

tests:
  graten-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-name-shadowing
    dependencies:
    - graten
    - HUnit                >= 1.6      && < 2.0
    - test-framework       == 0.8.*
    - test-framework-hunit == 0.3.*
    - text                 >= 1.2.5.0  && < 3.0
